// you can convert any string valu as numberic.
// parseFloat (Parse Float) :

// var x = '10'; (This valu is numbaric but i used string so the out put will be string )
//               (But if i used ParseFloat it will convert to numbaric)

// Example :

// var x = '10';
// x = parseFloat(x)
// console.log(typeof x);

// Example :
// var x = '5.00';
// convert = parseInt(x)
// console.log(convert); (result will be just '5' beacuse it parsInt is pornosonkha !)
